import argparse
import os
import shutil
from dotenv import load_dotenv
from pathlib import Path

from huggingface_hub import HfApi, login
from llmcompressor import oneshot
from llmcompressor.modifiers.awq import AWQModifier

load_dotenv()

def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Quantize an LLM to AWQ 4-bit using llm-compressor and push to Hugging Face.")
    
    parser.add_argument(
        "--model", 
        type=str, 
        required=True, 
        help="Source HuggingFace model ID (e.g., 'Qwen/Qwen2.5-7B-Instruct')"
    )
    parser.add_argument(
        "--repo-id", 
        type=str, 
        required=True, 
        help="Destination HuggingFace repo ID (e.g., 'your-username/Qwen2.5-7B-Instruct-AWQ')"
    )
    parser.add_argument(
        "--dataset",
        type=str,
        default="open_platypus",
        help="Dataset used for AWQ calibration (default: open_platypus)"
    )
    parser.add_argument(
        "--samples", 
        type=int, 
        default=512, 
        help="Number of calibration samples to use (default: 512)"
    )
    parser.add_argument(
        "--seq-len", 
        type=int, 
        default=2048, 
        help="Max sequence length for calibration (default: 2048)"
    )
    parser.add_argument(
        "--temp-dir", 
        type=str, 
        default="./quantized_temp", 
        help="Temporary local directory to store quantized weights before upload"
    )
    
    return parser

def _authenticate_hf():
    """Authenticates with Hugging Face using env variables."""
    hf_token = os.environ.get("HUGGINGFACE_API_KEY") or os.environ.get("HF_TOKEN")
    
    if not hf_token:
        raise ValueError(
            "Authentication token not found! Please set the HUGGINGFACE_API_KEY "
            "or HF_TOKEN environment variable."
        )
    
    login(token=hf_token)
    print("Successfully authenticated with Hugging Face.")

def main():
    parser = _build_parser()
    args = parser.parse_args()

    # 1. Authenticate
    _authenticate_hf()

    print(f"--- Starting AWQ Quantization for {args.model} using llm-compressor ---")

    # 2. Define the AWQ Recipe
    # W4A16_ASYM = 4-bit asymmetric weights with 16-bit activations (The standard AWQ format)
    recipe = [
        AWQModifier(
            targets=["Linear"], 
            scheme="W4A16_ASYM", 
            ignore=["lm_head"] 
        )
    ]

    # 3. Apply Oneshot Compression
    # This automatically loads the model, applies calibration, and saves to disk.
    print(f"Running oneshot quantization with {args.samples} samples from '{args.dataset}'...")
    oneshot(
        model=args.model,
        dataset=args.dataset,
        recipe=recipe,
        max_seq_length=args.seq_len,
        num_calibration_samples=args.samples,
        output_dir=args.temp_dir,
    )

    # 4. Push to Hugging Face
    print(f"Pushing quantized model to Hugging Face Hub: {args.repo_id}...")
    api = HfApi()
    
    # Create the repo if it doesn't exist
    api.create_repo(repo_id=args.repo_id, exist_ok=True, private=False)
    
    # Upload the entire folder generated by llm-compressor
    api.upload_folder(
        folder_path=args.temp_dir,
        repo_id=args.repo_id,
        commit_message=f"Upload AWQ 4-bit quantization of {args.model} via llm-compressor"
    )

    # 5. Cleanup
    print("Upload complete! Cleaning up local files...")
    if os.path.exists(args.temp_dir):
        shutil.rmtree(args.temp_dir)
    
    print(f"Success! Model is available at: https://huggingface.co/{args.repo_id}")

if __name__ == "__main__":
    main()